name: Docker Bake
description: General Docker Bake target executor.

inputs:
  target:
    description: Bake target to execute.
    required: true
  
runs:
  using: composite

  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
      with:
        cache-binary: false
        use: true

    - name: Bake target:(${{ inputs.target }})
      uses: docker/bake-action@v7
      with:
        source: https://github.com/${{ github.repository }}.git#${{ github.sha }}
        targets: ${{ inputs.target }}

      env:
        BUILDX_BAKE_GIT_AUTH_TOKEN: ${{ github.token }}