use super::env_var_core::{EnvVarHostMapping, EnvVarImportMode, EnvVarSource};
#[allow(clippy::wildcard_imports)]
use super::env_var_host::*;

#[cfg(any(target_os = "linux", test))]
pub const LINUX_MAPPINGS: &[EnvVarHostMapping] = &[
    EnvVarHostMapping {
        key: HOSTNAME_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOSTNAME_ENV_VAR.key],
        fallback: None,
    },
    EnvVarHostMapping {
        key: WORKDIR_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[WORKDIR_ENV_VAR.key, "PWD"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: PATH_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[HOME_DATA_BIN_ENV_VAR.key, PATH_ENV_VAR.key],
        alias_import_mode: EnvVarImportMode::Merge,
        alias_export: &[PATH_ENV_VAR.key],
        fallback: None,
    },
    // User
    EnvVarHostMapping {
        key: USER_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[USER_ENV_VAR.key],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[USER_ENV_VAR.key],
        fallback: None,
    },
    EnvVarHostMapping {
        key: USER_LANGUAGE_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[USER_LANGUAGE_ENV_VAR.key, "LANG"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[USER_LANGUAGE_ENV_VAR.key, "LANG"],
        fallback: Some("C.UTF-8"),
    },
    EnvVarHostMapping {
        key: USER_TIMEZONE_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[USER_TIMEZONE_ENV_VAR.key, "TZ"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[USER_TIMEZONE_ENV_VAR.key, "TZ"],
        fallback: None,
    },
    // Home directories
    EnvVarHostMapping {
        key: HOME_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOME_ENV_VAR.key],
        fallback: None,
    },
    EnvVarHostMapping {
        key: HOME_TEMP_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOME_TEMP_ENV_VAR.key, "TEMP", "TMPDIR", "TMP"],
        fallback: Some("~/.tmp"),
    },
    EnvVarHostMapping {
        key: HOME_CONFIG_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOME_CONFIG_ENV_VAR.key, "XDG_CONFIG_HOME"],
        fallback: Some("~/.config"),
    },
    EnvVarHostMapping {
        key: HOME_DATA_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOME_DATA_ENV_VAR.key, "XDG_DATA_HOME"],
        fallback: Some("~/.local/share"),
    },
    EnvVarHostMapping {
        key: HOME_DATA_BIN_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOME_DATA_BIN_ENV_VAR.key],
        fallback: Some("~/.local/bin"),
    },
    EnvVarHostMapping {
        key: HOME_CACHE_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOME_CACHE_ENV_VAR.key, "XDG_CACHE_HOME", "CACHE"],
        fallback: Some("~/.cache"),
    },
    EnvVarHostMapping {
        key: HOME_STATE_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOME_STATE_ENV_VAR.key, "XDG_STATE_HOME"],
        fallback: Some("~/.local/state"),
    },
    EnvVarHostMapping {
        key: HOME_SESSION_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOME_SESSION_ENV_VAR.key, "XDG_RUNTIME_DIR"],
        fallback: Some("~/.session"),
    },
    // Terminal
    EnvVarHostMapping {
        key: TERMINAL_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[TERMINAL_ENV_VAR.key, "SHELL"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &["SHELL"],
        fallback: Some("sh"),
    },
    EnvVarHostMapping {
        key: TERMINAL_TYPE_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[TERMINAL_TYPE_ENV_VAR.key, "TERM"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &["TERM"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: TERMINAL_COLOR_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[TERMINAL_COLOR_ENV_VAR.key, "COLORTERM"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &["COLORTERM"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: TERMINAL_NOCOLOR_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &["NO_COLOR"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &["NO_COLOR"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: TERMINAL_PROGRAM_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &["TERM_PROGRAM"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &["TERM_PROGRAM"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: TERMINAL_PROGRAM_VERSION_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &["TERM_PROGRAM_VERSION"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &["TERM_PROGRAM_VERSION"],
        fallback: None,
    },
    // Platform
    EnvVarHostMapping {
        key: PLATFORM_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[PLATFORM_ENV_VAR.key],
        fallback: Some(std::env::consts::OS),
    },
    EnvVarHostMapping {
        key: PLATFORM_FAMILY_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[PLATFORM_FAMILY_ENV_VAR.key],
        fallback: Some(std::env::consts::FAMILY),
    },
    EnvVarHostMapping {
        key: PLATFORM_ARCH_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[PLATFORM_ARCH_ENV_VAR.key],
        fallback: Some(std::env::consts::ARCH),
    },
    EnvVarHostMapping {
        key: PLATFORM_VERSION_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[PLATFORM_VERSION_ENV_VAR.key],
        fallback: None,
    },
    EnvVarHostMapping {
        key: PLATFORM_KERNEL_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[PLATFORM_KERNEL_ENV_VAR.key],
        fallback: Some("Linux"),
    },
    EnvVarHostMapping {
        key: PLATFORM_KERNEL_VERSION_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[PLATFORM_KERNEL_VERSION_ENV_VAR.key],
        fallback: None,
    },
];
