use super::env_var_core::{EnvVarHostMapping, EnvVarImportMode, EnvVarSource};
#[allow(clippy::wildcard_imports)]
use super::env_var_host::*;

#[cfg(any(target_os = "windows", test))]
pub const WINDOWS_MAPPINGS: &[EnvVarHostMapping] = &[
    EnvVarHostMapping {
        key: HOSTNAME_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[HOSTNAME_ENV_VAR.key, "COMPUTERNAME"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOSTNAME_ENV_VAR.key, "COMPUTERNAME"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: WORKDIR_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[WORKDIR_ENV_VAR.key, "CD"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: PATH_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[HOME_DATA_BIN_ENV_VAR.key, PATH_ENV_VAR.key],
        alias_import_mode: EnvVarImportMode::Merge,
        alias_export: &[PATH_ENV_VAR.key],
        fallback: None,
    },
    // User
    EnvVarHostMapping {
        key: USER_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[USER_ENV_VAR.key, "USERNAME"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[USER_ENV_VAR.key, "USERNAME"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: USER_LANGUAGE_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[USER_LANGUAGE_ENV_VAR.key, "LANG"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[USER_LANGUAGE_ENV_VAR.key, "LANG"],
        fallback: Some("en_US.UTF-8"),
    },
    EnvVarHostMapping {
        key: USER_TIMEZONE_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[USER_TIMEZONE_ENV_VAR.key, "TZ"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[USER_TIMEZONE_ENV_VAR.key, "TZ"],
        fallback: None,
    },
    // Home directories
    EnvVarHostMapping {
        key: HOME_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOME_ENV_VAR.key, "USERPROFILE", "HOMEPATH"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: HOME_TEMP_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOME_TEMP_ENV_VAR.key, "TEMP", "TMP"],
        fallback: Some(r"~\AppData\Local\Temp"),
    },
    EnvVarHostMapping {
        key: HOME_CONFIG_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOME_CONFIG_ENV_VAR.key, "APPDATA"],
        fallback: Some(r"~\AppData\Roaming"),
    },
    EnvVarHostMapping {
        key: HOME_DATA_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOME_DATA_ENV_VAR.key, "LOCALAPPDATA"],
        fallback: Some(r"~\AppData\Local"),
    },
    EnvVarHostMapping {
        key: HOME_DATA_BIN_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOME_DATA_BIN_ENV_VAR.key],
        fallback: Some(r"~\.local\bin"),
    },
    EnvVarHostMapping {
        key: HOME_CACHE_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOME_CACHE_ENV_VAR.key, "CACHE"],
        fallback: Some(r"~\AppData\Local\Temp"),
    },
    EnvVarHostMapping {
        key: HOME_STATE_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOME_STATE_ENV_VAR.key],
        fallback: Some(r"~\AppData\Local"),
    },
    EnvVarHostMapping {
        key: HOME_SESSION_ENV_VAR.key,
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[HOME_SESSION_ENV_VAR.key],
        fallback: Some(r"~\AppData\Local\Temp"),
    },
    // Terminal
    EnvVarHostMapping {
        key: TERMINAL_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[TERMINAL_ENV_VAR.key, "COMSPEC", "SHELL"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &["COMSPEC", "SHELL"],
        fallback: Some("cmd.exe"),
    },
    EnvVarHostMapping {
        key: TERMINAL_TYPE_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[TERMINAL_TYPE_ENV_VAR.key, "TERM"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &["TERM"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: TERMINAL_COLOR_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[TERMINAL_COLOR_ENV_VAR.key, "COLORTERM"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &["COLORTERM"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: TERMINAL_NOCOLOR_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &["NO_COLOR"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &["NO_COLOR"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: TERMINAL_PROGRAM_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &["TERM_PROGRAM"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &["TERM_PROGRAM"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: TERMINAL_PROGRAM_VERSION_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &["TERM_PROGRAM_VERSION"],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &["TERM_PROGRAM_VERSION"],
        fallback: None,
    },
    // Platform
    EnvVarHostMapping {
        key: PLATFORM_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[PLATFORM_ENV_VAR.key],
        fallback: Some(std::env::consts::OS),
    },
    EnvVarHostMapping {
        key: PLATFORM_FAMILY_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[PLATFORM_FAMILY_ENV_VAR.key],
        fallback: Some(std::env::consts::FAMILY),
    },
    EnvVarHostMapping {
        key: PLATFORM_ARCH_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[PLATFORM_ARCH_ENV_VAR.key],
        fallback: Some(std::env::consts::ARCH),
    },
    EnvVarHostMapping {
        key: PLATFORM_VERSION_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[PLATFORM_VERSION_ENV_VAR.key],
        fallback: None,
    },
    EnvVarHostMapping {
        key: PLATFORM_KERNEL_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[PLATFORM_KERNEL_ENV_VAR.key],
        fallback: Some("Windows_NT"),
    },
    EnvVarHostMapping {
        key: PLATFORM_KERNEL_VERSION_ENV_VAR.key,
        source: EnvVarSource::Host,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &[PLATFORM_KERNEL_VERSION_ENV_VAR.key],
        fallback: None,
    },
    // Windows specific (no cross-platform equivalent)
    EnvVarHostMapping {
        key: "ProgramFiles",
        source: EnvVarSource::Host,
        alias_import: &["ProgramFiles"],
        alias_import_mode: EnvVarImportMode::PassThrough,
        alias_export: &["ProgramFiles"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: "ProgramFiles(x86)",
        source: EnvVarSource::Host,
        alias_import: &["ProgramFiles(x86)"],
        alias_import_mode: EnvVarImportMode::PassThrough,
        alias_export: &["ProgramFiles(x86)"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: "ProgramFiles(Arm)",
        source: EnvVarSource::Host,
        alias_import: &["ProgramFiles(Arm)"],
        alias_import_mode: EnvVarImportMode::PassThrough,
        alias_export: &["ProgramFiles(Arm)"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: "ProgramW6432",
        source: EnvVarSource::Host,
        alias_import: &["ProgramW6432"],
        alias_import_mode: EnvVarImportMode::PassThrough,
        alias_export: &["ProgramW6432"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: "CommonProgramFiles",
        source: EnvVarSource::Host,
        alias_import: &["CommonProgramFiles"],
        alias_import_mode: EnvVarImportMode::PassThrough,
        alias_export: &["CommonProgramFiles"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: "CommonProgramFiles(x86)",
        source: EnvVarSource::Host,
        alias_import: &["CommonProgramFiles(x86)"],
        alias_import_mode: EnvVarImportMode::PassThrough,
        alias_export: &["CommonProgramFiles(x86)"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: "CommonProgramW6432",
        source: EnvVarSource::Host,
        alias_import: &["CommonProgramW6432"],
        alias_import_mode: EnvVarImportMode::PassThrough,
        alias_export: &["CommonProgramW6432"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: "ProgramData",
        source: EnvVarSource::Provided,
        alias_import: &[],
        alias_import_mode: EnvVarImportMode::FirstFound,
        alias_export: &["ProgramData", "ALLUSERSPROFILE"],
        fallback: Some(r"~\AppData\ProgramData"),
    },
    EnvVarHostMapping {
        key: "SystemRoot",
        source: EnvVarSource::Host,
        alias_import: &["SystemRoot"],
        alias_import_mode: EnvVarImportMode::PassThrough,
        alias_export: &["SystemRoot"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: "windir",
        source: EnvVarSource::Host,
        alias_import: &["windir"],
        alias_import_mode: EnvVarImportMode::PassThrough,
        alias_export: &["windir"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: "SystemDrive",
        source: EnvVarSource::Host,
        alias_import: &["SystemDrive"],
        alias_import_mode: EnvVarImportMode::PassThrough,
        alias_export: &["SystemDrive"],
        fallback: None,
    },
    EnvVarHostMapping {
        key: "PATHEXT",
        source: EnvVarSource::Host,
        alias_import: &["PATHEXT"],
        alias_import_mode: EnvVarImportMode::PassThrough,
        alias_export: &["PATHEXT"],
        fallback: None,
    },
];
