name: Pull Request 

on:
  pull_request:
    paths-ignore:
      - **/*.md

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-amd:
    name: Quality Gates - Linux (amd64)
    runs-on: ubuntu-26.04
    steps:
      - uses: $/.github/actions/bake
        with:
          target: linux-amd64

  build-arm:
    name:  Quality Gates - Linux (arm64)
    runs-on: ubuntu-26.04-arm
    steps:
      - uses: $/.github/actions/bake
        with:
          target: linux-arm64