name: Pull Request 

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build - ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-26.04
            target: linux-amd64

          - runner: ubuntu-26.04-arm
            target: linux-arm64

          - runner: windows-2025
            target: windows-amd64
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/docker-bake
        with:
          bake-target: ${{ matrix.target }}
